export const POPULAR_ITEMS = [
  { id: "T4_BAG", name: "Bolsa do Recruta (T4)" },
  { id: "T5_BAG", name: "Bolsa do Especialista (T5)" },
  { id: "T6_BAG", name: "Bolsa do Perito (T6)" },
  { id: "T7_BAG", name: "Bolsa do Mestre (T7)" },
  { id: "T8_BAG", name: "Bolsa do Grão-Mestre (T8)" },
  { id: "T4_BAG@1", name: "Bolsa do Recruta (T4.1)" },
  { id: "T4_BAG@2", name: "Bolsa do Recruta (T4.2)" },
  { id: "T4_BAG@3", name: "Bolsa do Recruta (T4.3)" },
  { id: "T5_BAG@1", name: "Bolsa do Especialista (T5.1)" },
  { id: "T5_BAG@2", name: "Bolsa do Especialista (T5.2)" },
  { id: "T5_BAG@3", name: "Bolsa do Especialista (T5.3)" },
  { id: "T6_BAG@1", name: "Bolsa do Perito (T6.1)" },
  { id: "T6_BAG@2", name: "Bolsa do Perito (T6.2)" },
  { id: "T6_BAG@3", name: "Bolsa do Perito (T6.3)" },
  { id: "T4_CAPE", name: "Capa do Recruta (T4)" },
  { id: "T5_CAPE", name: "Capa do Especialista (T5)" },
  { id: "T6_CAPE", name: "Capa do Perito (T6)" },
  { id: "T7_CAPE", name: "Capa do Mestre (T7)" },
  { id: "T8_CAPE", name: "Capa do Grão-Mestre (T8)" },
  { id: "T4_MOUNT_HORSE", name: "Cavalo de Montaria (T4)" },
  { id: "T5_MOUNT_HORSE", name: "Cavalo de Montaria (T5)" },
  { id: "T6_MOUNT_HORSE", name: "Cavalo de Montaria (T6)" },
  { id: "T7_MOUNT_HORSE", name: "Cavalo de Montaria (T7)" },
  { id: "T8_MOUNT_HORSE", name: "Cavalo de Montaria (T8)" },
  { id: "T4_MOUNT_OX", name: "Boi de Transporte (T4)" },
  { id: "T5_MOUNT_OX", name: "Boi de Transporte (T5)" },
  { id: "T6_MOUNT_OX", name: "Boi de Transporte (T6)" },
  { id: "T7_MOUNT_OX", name: "Boi de Transporte (T7)" },
  { id: "T8_MOUNT_OX", name: "Boi de Transporte (T8)" },
  { id: "T5_HEAD_PLATE_SET1", name: "Elmo de Soldado (T5)" },
  { id: "T7_HEAD_PLATE_SET1", name: "Elmo de Soldado (T7)" },
  { id: "T5_ARMOR_PLATE_SET1", name: "Armadura de Soldado (T5)" },
  { id: "T7_ARMOR_PLATE_SET1", name: "Armadura de Soldado (T7)" },
  { id: "T4_ARMOR_PLATE_SET1@1", name: "Armadura de Soldado (T4.1)" },
  { id: "T4_ARMOR_PLATE_SET1@2", name: "Armadura de Soldado (T4.2)" },
  { id: "T4_ARMOR_PLATE_SET1@3", name: "Armadura de Soldado (T4.3)" },
  { id: "T5_ARMOR_PLATE_SET1@1", name: "Armadura de Soldado (T5.1)" },
  { id: "T5_ARMOR_PLATE_SET1@2", name: "Armadura de Soldado (T5.2)" },
  { id: "T5_ARMOR_PLATE_SET1@3", name: "Armadura de Soldado (T5.3)" },
  { id: "T6_ARMOR_PLATE_SET1@1", name: "Armadura de Soldado (T6.1)" },
  { id: "T6_ARMOR_PLATE_SET1@2", name: "Armadura de Soldado (T6.2)" },
  { id: "T6_ARMOR_PLATE_SET1@3", name: "Armadura de Soldado (T6.3)" },
  { id: "T5_SHOES_PLATE_SET1", name: "Botas de Soldado (T5)" },
  { id: "T7_SHOES_PLATE_SET1", name: "Botas de Soldado (T7)" },
  { id: "T4_MAIN_SWORD", name: "Espada Larga (T4)" },
  { id: "T5_MAIN_SWORD", name: "Espada Larga (T5)" },
  { id: "T6_MAIN_SWORD", name: "Espada Larga (T6)" },
  { id: "T7_MAIN_SWORD", name: "Espada Larga (T7)" },
  { id: "T8_MAIN_SWORD", name: "Espada Larga (T8)" },
  { id: "T4_MAIN_SWORD@1", name: "Espada Larga (T4.1)" },
  { id: "T4_MAIN_SWORD@2", name: "Espada Larga (T4.2)" },
  { id: "T4_MAIN_SWORD@3", name: "Espada Larga (T4.3)" },
  { id: "T5_MAIN_SWORD@1", name: "Espada Larga (T5.1)" },
  { id: "T5_MAIN_SWORD@2", name: "Espada Larga (T5.2)" },
  { id: "T5_MAIN_SWORD@3", name: "Espada Larga (T5.3)" },
  { id: "T6_MAIN_SWORD@1", name: "Espada Larga (T6.1)" },
  { id: "T6_MAIN_SWORD@2", name: "Espada Larga (T6.2)" },
  { id: "T8_MAIN_SWORD@3", name: "Espada Larga (T6.3)" },
  { id: "T4_MAIN_AXE", name: "Machado de Batalha (T4)" },
  { id: "T5_WOOD", name: "Tábuas de Cedro (T5)" },
  { id: "T6_WOOD", name: "Tábuas de Bloqueio (T6)" },
  { id: "T7_WOOD", name: "Tábuas de Carvalho (T7)" },
  { id: "T8_WOOD", name: "Tábuas de Whitewood (T8)" },
  { id: "T4_STONEBLOCK", name: "Blocos de Calcário (T4)" },
  { id: "T5_STONEBLOCK", name: "Blocos de Arenito (T5)" },
  { id: "T6_STONEBLOCK", name: "Blocos de Ardósia (T6)" },
  { id: "T7_STONEBLOCK", name: "Blocos de Basalto (T7)" },
  { id: "T8_STONEBLOCK", name: "Blocos de Mármore (T8)" },
  { id: "T4_LEATHER", name: "Couro Curvado (T4)" },
  { id: "T5_LEATHER", name: "Couro Refinado (T5)" },
  { id: "T6_LEATHER", name: "Couro Gravado (T6)" },
  { id: "T7_LEATHER", name: "Couro Reforçado (T7)" },
  { id: "T8_LEATHER", name: "Couro de Grão-Mestre (T8)" },
  { id: "T4_CLOTH", name: "Tecido de Linho (T4)" },
  { id: "T5_CLOTH", name: "Tecido de Seda (T5)" },
  { id: "T6_CLOTH", name: "Tecido de Veludo (T6)" },
  { id: "T7_CLOTH", name: "Tecido de Cetim (T7)" },
  { id: "T8_CLOTH", name: "Tecido de Grão-Mestre (T8)" },
  { id: "T4_METALBAR", name: "Barra de Aço (T4)" },
  { id: "T5_METALBAR", name: "Barra de Titânio (T5)" },
  { id: "T6_METALBAR", name: "Barra de Runas (T6)" },
  { id: "T7_METALBAR", name: "Barra de Meteorito (T7)" },
  { id: "T8_METALBAR", name: "Barra de Adamantio (T8)" },
  // Artifacts & Runes
  { id: "T4_RUNE", name: "Runa (T4)" },
  { id: "T5_RUNE", name: "Runa (T5)" },
  { id: "T6_RUNE", name: "Runa (T6)" },
  { id: "T7_RUNE", name: "Runa (T7)" },
  { id: "T8_RUNE", name: "Runa (T8)" },
  { id: "T4_SOUL", name: "Alma (T4)" },
  { id: "T5_SOUL", name: "Alma (T5)" },
  { id: "T6_SOUL", name: "Alma (T6)" },
  { id: "T7_SOUL", name: "Alma (T7)" },
  { id: "T8_SOUL", name: "Alma (T8)" },
  { id: "T4_RELIC", name: "Relíquia (T4)" },
  { id: "T5_RELIC", name: "Relíquia (T5)" },
  { id: "T6_RELIC", name: "Relíquia (T6)" },
  { id: "T7_RELIC", name: "Relíquia (T7)" },
  { id: "T8_RELIC", name: "Relíquia (T8)" },
  // Mounts
  { id: "T3_MOUNT_HORSE", name: "Cavalo de Montaria (T3)" },
  { id: "T3_MOUNT_OX", name: "Boi de Transporte (T3)" },
  { id: "T5_MOUNT_ARMORED_HORSE", name: "Cavalo Blindado (T5)" },
  { id: "T6_MOUNT_ARMORED_HORSE", name: "Cavalo Blindado (T6)" },
  { id: "T7_MOUNT_ARMORED_HORSE", name: "Cavalo Blindado (T7)" },
  { id: "T8_MOUNT_ARMORED_HORSE", name: "Cavalo Blindado (T8)" },
  { id: "T6_MOUNT_DIREWOLF", name: "Lobo Vil (T6)" },
  { id: "T7_MOUNT_SWAMPDRAGON", name: "Dragão do Pântano (T7)" },
  { id: "T8_MOUNT_DIREBEAR", name: "Urso Vil (T8)" },
  // Artifacts
  { id: "T4_ARTEFACT_MAIN_SWORD_HELL", name: "Lâmina Infernal (T4)" },
  { id: "T6_ARTEFACT_MAIN_SWORD_HELL", name: "Lâmina Infernal (T6)" },
  { id: "T8_ARTEFACT_MAIN_SWORD_HELL", name: "Lâmina Infernal (T8)" },
  { id: "T4_ARTEFACT_2H_BOW_HELL", name: "Arco de Alma (T4)" },
  { id: "T6_ARTEFACT_2H_BOW_HELL", name: "Arco de Alma (T6)" },
  { id: "T8_ARTEFACT_2H_BOW_HELL", name: "Arco de Alma (T8)" },
  { id: "T4_ARTEFACT_MAIN_FIRESTAFF_HELL", name: "Cajado de Fogo Infernal (T4)" },
  { id: "T6_ARTEFACT_MAIN_FIRESTAFF_HELL", name: "Cajado de Fogo Infernal (T6)" },
  { id: "T8_ARTEFACT_MAIN_FIRESTAFF_HELL", name: "Cajado de Fogo Infernal (T8)" },
  // Avalonian
  { id: "T4_MAIN_SWORD_AVALON", name: "Espada de Avalonian (T4)" },
  { id: "T6_MAIN_SWORD_AVALON", name: "Espada de Avalonian (T6)" },
  { id: "T8_MAIN_SWORD_AVALON", name: "Espada de Avalonian (T8)" },
  { id: "T4_2H_BOW_AVALON", name: "Arco de Avalonian (T4)" },
  { id: "T6_2H_BOW_AVALON", name: "Arco de Avalonian (T6)" },
  { id: "T8_2H_BOW_AVALON", name: "Arco de Avalonian (T8)" },
  // Food & Potions
  { id: "T4_FOOD_SOUP", name: "Sopa de Trigo (T4)" },
  { id: "T6_FOOD_SOUP", name: "Sopa de Repolho (T6)" },
  { id: "T8_FOOD_SOUP", name: "Sopa de Grão-Mestre (T8)" },
  { id: "T4_POTION_COOLDOWN", name: "Poção de Recarga (T4)" },
  { id: "T6_POTION_COOLDOWN", name: "Poção de Recarga (T6)" },
  { id: "T4_POTION_STONESKIN", name: "Poção de Pele de Pedra (T4)" },
  { id: "T6_POTION_STONESKIN", name: "Poção de Pele de Pedra (T6)" },
  { id: "T4_POTION_SLOWFIELD", name: "Poção de Campo de Lentidão (T4)" },
  { id: "T6_POTION_SLOWFIELD", name: "Poção de Campo de Lentidão (T6)" },
  // Seeds & Crops
  { id: "T1_CARROT_SEED", name: "Semente de Cenoura (T1)" },
  { id: "T2_BEAN_SEED", name: "Semente de Feijão (T2)" },
  { id: "T3_WHEAT_SEED", name: "Semente de Trigo (T3)" },
  { id: "T4_TURNIP_SEED", name: "Semente de Nabo (T4)" },
  { id: "T5_CABBAGE_SEED", name: "Semente de Repolho (T5)" },
  { id: "T6_POTATO_SEED", name: "Semente de Batata (T6)" },
  { id: "T7_CORN_SEED", name: "Semente de Milho (T7)" },
  { id: "T8_PUMPKIN_SEED", name: "Semente de Abóbora (T8)" },
  { id: "T1_CARROT", name: "Cenoura (T1)" },
  { id: "T2_BEAN", name: "Feijão (T2)" },
  { id: "T3_WHEAT", name: "Trigo (T3)" },
  { id: "T4_TURNIP", name: "Nabo (T4)" },
  { id: "T5_CABBAGE", name: "Repolho (T5)" },
  { id: "T6_POTATO", name: "Batata (T6)" },
  { id: "T7_CORN", name: "Milho (T7)" },
  { id: "T8_PUMPKIN", name: "Abóbora (T8)" },
  // Animals (Livestock)
  { id: "T3_FARM_CHICKEN_BABY", name: "Pinto (T3)" },
  { id: "T4_FARM_GOAT_BABY", name: "Cabrito (T4)" },
  { id: "T5_FARM_GOOSE_BABY", name: "Gansinho (T5)" },
  { id: "T6_FARM_PIG_BABY", name: "Leitão (T6)" },
  { id: "T7_FARM_COW_BABY", name: "Bezerro (T7)" },
  { id: "T3_FARM_CHICKEN", name: "Galinha (T3)" },
  { id: "T4_FARM_GOAT", name: "Cabra (T4)" },
  { id: "T5_FARM_GOOSE", name: "Ganso (T5)" },
  { id: "T6_FARM_PIG", name: "Porco (T6)" },
  { id: "T7_FARM_COW", name: "Vaca (T7)" },
  // More Mounts
  { id: "T5_MOUNT_SWAMPDRAGON_BABY", name: "Filhote de Dragão do Pântano (T5)" },
  { id: "T6_MOUNT_DIREWOLF_BABY", name: "Filhote de Lobo Vil (T6)" },
  { id: "T7_MOUNT_DIREBOAR_BABY", name: "Filhote de Javali Vil (T7)" },
  { id: "T8_MOUNT_DIREBEAR_BABY", name: "Filhote de Urso Vil (T8)" },
  // Rare Mounts
  { id: "T7_MOUNT_GIANTLIZARD_HERETIC", name: "Lagarto Gigante (T7)" },
  { id: "T6_MOUNT_MOOSE", name: "Alce (T6)" },
  { id: "T6_MOUNT_DIREBOAR", name: "Javali Vil (T6)" },
  { id: "T7_MOUNT_DIREBOAR", name: "Javali Vil (T7)" },
  { id: "T8_MOUNT_DIREBOAR", name: "Javali Vil (T8)" },
  // Herbs
  { id: "T2_AGARIC", name: "Cogumelo (T2)" },
  { id: "T3_COMFREY", name: "Confrei (T3)" },
  { id: "T4_BURDOCK", name: "Bardana (T4)" },
  { id: "T5_TEASEL", name: "Cardo (T5)" },
  { id: "T6_FOXGLOVE", name: "Dedaleira (T6)" },
  { id: "T7_MULLEIN", name: "Verbasco (T7)" },
  { id: "T8_YARROW", name: "Milefólio (T8)" },
  // More Food
  { id: "T3_FOOD_PIE", name: "Torta de Frango (T3)" },
  { id: "T5_FOOD_PIE", name: "Torta de Ganso (T5)" },
  { id: "T7_FOOD_PIE", name: "Torta de Porco (T7)" },
  { id: "T8_FOOD_PIE", name: "Torta de Grão-Mestre (T8)" },
  { id: "T4_FOOD_SANDWICH", name: "Sanduíche de Cabra (T4)" },
  { id: "T6_FOOD_SANDWICH", name: "Sanduíche de Boi (T6)" },
  { id: "T8_FOOD_SANDWICH", name: "Sanduíche de Grão-Mestre (T8)" },
  { id: "T7_FOOD_STEW_AVALON", name: "Gisado de Avalonian (T7)" },
  { id: "T8_FOOD_STEW_AVALON", name: "Gisado de Avalonian (T8)" },
  { id: "T7_FOOD_SANDWICH_AVALON", name: "Sanduíche de Avalonian (T7)" },
  { id: "T8_FOOD_SANDWICH_AVALON", name: "Sanduíche de Avalonian (T8)" },
  { id: "T7_FOOD_OMELETTE_AVALON", name: "Omelete de Avalonian (T7)" },
  { id: "T8_FOOD_OMELETTE_AVALON", name: "Omelete de Avalonian (T8)" },
  // Fish
  { id: "T4_FISH_FRESHWATER_ALLIGATOR_COMMON", name: "Jacaré de Água Doce (T4)" },
  { id: "T6_FISH_FRESHWATER_ALLIGATOR_COMMON", name: "Jacaré de Água Doce (T6)" },
  { id: "T8_FISH_FRESHWATER_ALLIGATOR_COMMON", name: "Jacaré de Água Doce (T8)" },
  { id: "T4_FISH_SALTWATER_ALLIGATOR_COMMON", name: "Jacaré de Água Salgada (T4)" },
  { id: "T6_FISH_SALTWATER_ALLIGATOR_COMMON", name: "Jacaré de Água Salgada (T6)" },
  { id: "T8_FISH_SALTWATER_ALLIGATOR_COMMON", name: "Jacaré de Água Salgada (T8)" },
  // More Artifacts
  { id: "T4_ARTEFACT_2H_ICESTAFF_HELL", name: "Cajado de Gelo Infernal (T4)" },
  { id: "T6_ARTEFACT_2H_ICESTAFF_HELL", name: "Cajado de Gelo Infernal (T6)" },
  { id: "T8_ARTEFACT_2H_ICESTAFF_HELL", name: "Cajado de Gelo Infernal (T8)" },
  { id: "T4_ARTEFACT_2H_CURSESTAFF_HELL", name: "Cajado Amaldiçoado Infernal (T4)" },
  { id: "T6_ARTEFACT_2H_CURSESTAFF_HELL", name: "Cajado Amaldiçoado Infernal (T6)" },
  { id: "T8_ARTEFACT_2H_CURSESTAFF_HELL", name: "Cajado Amaldiçoado Infernal (T8)" },
  // Journals
  { id: "T4_MAIN_FIRESTAFF", name: "Cajado de Fogo (T4)" },
  { id: "T6_MAIN_FIRESTAFF", name: "Cajado de Fogo (T6)" },
  { id: "T8_MAIN_FIRESTAFF", name: "Cajado de Fogo (T8)" },
  { id: "T4_2H_FIRESTAFF", name: "Grande Cajado de Fogo (T4)" },
  { id: "T6_2H_FIRESTAFF", name: "Grande Cajado de Fogo (T6)" },
  { id: "T8_2H_FIRESTAFF", name: "Grande Cajado de Fogo (T8)" },
  { id: "T4_2H_INFERNOSTAFF", name: "Cajado Infernal (T4)" },
  { id: "T6_2H_INFERNOSTAFF", name: "Cajado Infernal (T6)" },
  { id: "T8_2H_INFERNOSTAFF", name: "Cajado Infernal (T8)" },
  // Holy Staffs
  { id: "T4_MAIN_HOLYSTAFF", name: "Cajado Sagrado (T4)" },
  { id: "T6_MAIN_HOLYSTAFF", name: "Cajado Sagrado (T6)" },
  { id: "T8_MAIN_HOLYSTAFF", name: "Cajado Sagrado (T8)" },
  { id: "T4_2H_HOLYSTAFF", name: "Grande Cajado Sagrado (T4)" },
  { id: "T6_2H_HOLYSTAFF", name: "Grande Cajado Sagrado (T6)" },
  { id: "T8_2H_HOLYSTAFF", name: "Grande Cajado Sagrado (T8)" },
  { id: "T4_2H_DIVINESTAFF", name: "Cajado Divino (T4)" },
  { id: "T6_2H_DIVINESTAFF", name: "Cajado Divino (T6)" },
  { id: "T8_2H_DIVINESTAFF", name: "Cajado Divino (T8)" },
  { id: "T4_2H_HOLYSTAFF_HELL", name: "Cajado da Vida (T4)" },
  { id: "T6_2H_HOLYSTAFF_HELL", name: "Cajado da Vida (T6)" },
  { id: "T8_2H_HOLYSTAFF_HELL", name: "Cajado da Vida (T8)" },
  { id: "T4_2H_HOLYSTAFF_UNDEAD", name: "Cajado da Redenção (T4)" },
  { id: "T6_2H_HOLYSTAFF_UNDEAD", name: "Cajado da Redenção (T6)" },
  { id: "T8_2H_HOLYSTAFF_UNDEAD", name: "Cajado da Redenção (T8)" },
  // Nature Staffs
  { id: "T4_MAIN_NATURESTAFF", name: "Cajado da Natureza (T4)" },
  { id: "T6_MAIN_NATURESTAFF", name: "Cajado da Natureza (T6)" },
  { id: "T8_MAIN_NATURESTAFF", name: "Cajado da Natureza (T8)" },
  { id: "T4_2H_NATURESTAFF", name: "Grande Cajado da Natureza (T4)" },
  { id: "T6_2H_NATURESTAFF", name: "Grande Cajado da Natureza (T6)" },
  { id: "T8_2H_NATURESTAFF", name: "Grande Cajado da Natureza (T8)" },
  { id: "T4_2H_WILDSTAFF", name: "Cajado Selvagem (T4)" },
  { id: "T6_2H_WILDSTAFF", name: "Cajado Selvagem (T6)" },
  { id: "T8_2H_WILDSTAFF", name: "Cajado Selvagem (T8)" },
  // Cloth Armor (Scholar)
  { id: "T4_HEAD_CLOTH_SET1", name: "Capuz do Estudioso (T4)" },
  { id: "T6_HEAD_CLOTH_SET1", name: "Capuz do Estudioso (T6)" },
  { id: "T8_HEAD_CLOTH_SET1", name: "Capuz do Estudioso (T8)" },
  { id: "T4_ARMOR_CLOTH_SET1", name: "Robe do Estudioso (T4)" },
  { id: "T6_ARMOR_CLOTH_SET1", name: "Robe do Estudioso (T6)" },
  { id: "T8_ARMOR_CLOTH_SET1", name: "Robe do Estudioso (T8)" },
  { id: "T4_SHOES_CLOTH_SET1", name: "Sandálias do Estudioso (T4)" },
  { id: "T6_SHOES_CLOTH_SET1", name: "Sandálias do Estudioso (T6)" },
  { id: "T8_SHOES_CLOTH_SET1", name: "Sandálias do Estudioso (T8)" },
  // Cloth Armor (Cleric)
  { id: "T4_HEAD_CLOTH_SET2", name: "Capuz do Clérigo (T4)" },
  { id: "T6_HEAD_CLOTH_SET2", name: "Capuz do Clérigo (T6)" },
  { id: "T8_HEAD_CLOTH_SET2", name: "Capuz do Clérigo (T8)" },
  { id: "T4_ARMOR_CLOTH_SET2", name: "Robe do Clérigo (T4)" },
  { id: "T6_ARMOR_CLOTH_SET2", name: "Robe do Clérigo (T6)" },
  { id: "T8_ARMOR_CLOTH_SET2", name: "Robe do Clérigo (T8)" },
  { id: "T4_SHOES_CLOTH_SET2", name: "Sandálias do Clérigo (T4)" },
  { id: "T6_SHOES_CLOTH_SET2", name: "Sandálias do Clérigo (T6)" },
  { id: "T8_SHOES_CLOTH_SET2", name: "Sandálias do Clérigo (T8)" },
  // Cloth Armor (Mage)
  { id: "T4_HEAD_CLOTH_SET3", name: "Capuz do Mago (T4)" },
  { id: "T6_HEAD_CLOTH_SET3", name: "Capuz do Mago (T6)" },
  { id: "T8_HEAD_CLOTH_SET3", name: "Capuz do Mago (T8)" },
  { id: "T4_ARMOR_CLOTH_SET3", name: "Robe do Mago (T4)" },
  { id: "T6_ARMOR_CLOTH_SET3", name: "Robe do Mago (T6)" },
  { id: "T8_ARMOR_CLOTH_SET3", name: "Robe do Mago (T8)" },
  { id: "T4_SHOES_CLOTH_SET3", name: "Sandálias do Mago (T4)" },
  { id: "T6_SHOES_CLOTH_SET3", name: "Sandálias do Mago (T6)" },
  { id: "T8_SHOES_CLOTH_SET3", name: "Sandálias do Mago (T8)" },
  // Leather Armor (Mercenary)
  { id: "T4_HEAD_LEATHER_SET1", name: "Capuz do Mercenário (T4)" },
  { id: "T6_HEAD_LEATHER_SET1", name: "Capuz do Mercenário (T6)" },
  { id: "T8_HEAD_LEATHER_SET1", name: "Capuz do Mercenário (T8)" },
  { id: "T4_ARMOR_LEATHER_SET1", name: "Jaqueta do Mercenário (T4)" },
  { id: "T6_ARMOR_LEATHER_SET1", name: "Jaqueta do Mercenário (T6)" },
  { id: "T8_ARMOR_LEATHER_SET1", name: "Jaqueta do Mercenário (T8)" },
  { id: "T4_SHOES_LEATHER_SET1", name: "Sapatos do Mercenário (T4)" },
  { id: "T6_SHOES_LEATHER_SET1", name: "Sapatos do Mercenário (T6)" },
  { id: "T8_SHOES_LEATHER_SET1", name: "Sapatos do Mercenário (T8)" },
  // Leather Armor (Assassin)
  { id: "T4_HEAD_LEATHER_SET2", name: "Capuz do Assassino (T4)" },
  { id: "T6_HEAD_LEATHER_SET2", name: "Capuz do Assassino (T6)" },
  { id: "T8_HEAD_LEATHER_SET2", name: "Capuz do Assassino (T8)" },
  { id: "T4_ARMOR_LEATHER_SET2", name: "Jaqueta do Assassino (T4)" },
  { id: "T6_ARMOR_LEATHER_SET2", name: "Jaqueta do Assassino (T6)" },
  { id: "T8_ARMOR_LEATHER_SET2", name: "Jaqueta do Assassino (T8)" },
  { id: "T4_SHOES_LEATHER_SET2", name: "Sapatos do Assassino (T4)" },
  { id: "T6_SHOES_LEATHER_SET2", name: "Sapatos do Assassino (T6)" },
  { id: "T8_SHOES_LEATHER_SET2", name: "Sapatos do Assassino (T8)" },
  // Leather Armor (Hunter)
  { id: "T4_HEAD_LEATHER_SET3", name: "Capuz do Caçador (T4)" },
  { id: "T6_HEAD_LEATHER_SET3", name: "Capuz do Caçador (T6)" },
  { id: "T8_HEAD_LEATHER_SET3", name: "Capuz do Caçador (T8)" },
  { id: "T4_ARMOR_LEATHER_SET3", name: "Jaqueta do Caçador (T4)" },
  { id: "T6_ARMOR_LEATHER_SET3", name: "Jaqueta do Caçador (T6)" },
  { id: "T8_ARMOR_LEATHER_SET3", name: "Jaqueta do Caçador (T8)" },
  { id: "T4_SHOES_LEATHER_SET3", name: "Sapatos do Caçador (T4)" },
  { id: "T6_SHOES_LEATHER_SET3", name: "Sapatos do Caçador (T6)" },
  { id: "T8_SHOES_LEATHER_SET3", name: "Sapatos do Caçador (T8)" },
  // Plate Armor (Soldier)
  { id: "T4_HEAD_PLATE_SET1", name: "Elmo do Soldado (T4)" },
  { id: "T6_HEAD_PLATE_SET1", name: "Elmo do Soldado (T6)" },
  { id: "T8_HEAD_PLATE_SET1", name: "Elmo do Soldado (T8)" },
  { id: "T4_ARMOR_PLATE_SET1", name: "Armadura do Soldado (T4)" },
  { id: "T6_ARMOR_PLATE_SET1", name: "Armadura do Soldado (T6)" },
  { id: "T8_ARMOR_PLATE_SET1", name: "Armadura do Soldado (T8)" },
  { id: "T4_SHOES_PLATE_SET1", name: "Botas do Soldado (T4)" },
  { id: "T6_SHOES_PLATE_SET1", name: "Botas do Soldado (T6)" },
  { id: "T8_SHOES_PLATE_SET1", name: "Botas do Soldado (T8)" },
  // Plate Armor (Knight)
  { id: "T4_HEAD_PLATE_SET2", name: "Elmo do Cavaleiro (T4)" },
  { id: "T6_HEAD_PLATE_SET2", name: "Elmo do Cavaleiro (T6)" },
  { id: "T8_HEAD_PLATE_SET2", name: "Elmo do Cavaleiro (T8)" },
  { id: "T4_ARMOR_PLATE_SET2", name: "Armadura do Cavaleiro (T4)" },
  { id: "T6_ARMOR_PLATE_SET2", name: "Armadura do Cavaleiro (T6)" },
  { id: "T8_ARMOR_PLATE_SET2", name: "Armadura do Cavaleiro (T8)" },
  { id: "T4_SHOES_PLATE_SET2", name: "Botas do Cavaleiro (T4)" },
  { id: "T6_SHOES_PLATE_SET2", name: "Botas do Cavaleiro (T6)" },
  { id: "T8_SHOES_PLATE_SET2", name: "Botas do Cavaleiro (T8)" },
  // Plate Armor (Guardian)
  { id: "T4_HEAD_PLATE_SET3", name: "Elmo do Guardião (T4)" },
  { id: "T6_HEAD_PLATE_SET3", name: "Elmo do Guardião (T6)" },
  { id: "T8_HEAD_PLATE_SET3", name: "Elmo do Guardião (T8)" },
  { id: "T4_ARMOR_PLATE_SET3", name: "Armadura do Guardião (T4)" },
  { id: "T6_ARMOR_PLATE_SET3", name: "Armadura do Guardião (T6)" },
  { id: "T8_ARMOR_PLATE_SET3", name: "Armadura do Guardião (T8)" },
  { id: "T4_SHOES_PLATE_SET3", name: "Botas do Guardião (T4)" },
  { id: "T6_SHOES_PLATE_SET3", name: "Botas do Guardião (T6)" },
  { id: "T8_SHOES_PLATE_SET3", name: "Botas do Guardião (T8)" },
  // Off-hands
  { id: "T4_OFF_SHIELD", name: "Escudo (T4)" },
  { id: "T6_OFF_SHIELD", name: "Escudo (T6)" },
  { id: "T8_OFF_SHIELD", name: "Escudo (T8)" },
  { id: "T4_OFF_SHIELD_HELL", name: "Sarcófago (T4)" },
  { id: "T6_OFF_SHIELD_HELL", name: "Sarcófago (T6)" },
  { id: "T8_OFF_SHIELD_HELL", name: "Sarcófago (T8)" },
  { id: "T4_OFF_SPIKEDSHIELD_MORGANA", name: "Quebra-Rosto (T4)" },
  { id: "T6_OFF_SPIKEDSHIELD_MORGANA", name: "Quebra-Rosto (T6)" },
  { id: "T8_OFF_SPIKEDSHIELD_MORGANA", name: "Quebra-Rosto (T8)" },
  { id: "T4_OFF_SHIELD_AVALON", name: "Égide Astral (T4)" },
  { id: "T6_OFF_SHIELD_AVALON", name: "Égide Astral (T6)" },
  { id: "T8_OFF_SHIELD_AVALON", name: "Égide Astral (T8)" },
  { id: "T4_OFF_BOOK", name: "Tomo de Feitiços (T4)" },
  { id: "T6_OFF_BOOK", name: "Tomo de Feitiços (T6)" },
  { id: "T8_OFF_BOOK", name: "Tomo de Feitiços (T8)" },
  { id: "T4_OFF_TORCH", name: "Tocha (T4)" },
  { id: "T6_OFF_TORCH", name: "Tocha (T6)" },
  { id: "T8_OFF_TORCH", name: "Tocha (T8)" },
  { id: "T4_OFF_ORB_MORGANA", name: "Olho de Segredo (T4)" },
  { id: "T6_OFF_ORB_MORGANA", name: "Olho de Segredo (T6)" },
  { id: "T8_OFF_ORB_MORGANA", name: "Olho de Segredo (T8)" },
  { id: "T4_OFF_DEMONSKULL_HELL", name: "Crânio de Muleta (T4)" },
  { id: "T6_OFF_DEMONSKULL_HELL", name: "Crânio de Muleta (T6)" },
  { id: "T8_OFF_DEMONSKULL_HELL", name: "Crânio de Muleta (T8)" },
  // Royal Armor
  { id: "T4_HEAD_ROYAL_SET1", name: "Capuz Real (T4)" },
  { id: "T6_HEAD_ROYAL_SET1", name: "Capuz Real (T6)" },
  { id: "T8_HEAD_ROYAL_SET1", name: "Capuz Real (T8)" },
  { id: "T4_ARMOR_ROYAL_SET1", name: "Casaco Real (T4)" },
  { id: "T6_ARMOR_ROYAL_SET1", name: "Casaco Real (T6)" },
  { id: "T8_ARMOR_ROYAL_SET1", name: "Casaco Real (T8)" },
  { id: "T4_SHOES_ROYAL_SET1", name: "Sapatos Reais (T4)" },
  { id: "T6_SHOES_ROYAL_SET1", name: "Sapatos Reais (T6)" },
  { id: "T8_SHOES_ROYAL_SET1", name: "Sapatos Reais (T8)" },
  // More Potions
  { id: "T4_POTION_RESIST", name: "Poção de Resistência (T4)" },
  { id: "T6_POTION_RESIST", name: "Poção de Resistência (T6)" },
  { id: "T4_POTION_GIGANT", name: "Poção Gigante (T4)" },
  { id: "T6_POTION_GIGANT", name: "Poção Gigante (T6)" },
  { id: "T4_POTION_STICKY", name: "Poção Pegajosa (T4)" },
  { id: "T6_POTION_STICKY", name: "Poção Pegajosa (T6)" },
  { id: "T4_POTION_INVIS", name: "Poção de Invisibilidade (T4)" },
  { id: "T6_POTION_INVIS", name: "Poção de Invisibilidade (T6)" },
  // More Food
  { id: "T4_FOOD_OMELETTE", name: "Omelete (T4)" },
  { id: "T6_FOOD_OMELETTE", name: "Omelete (T6)" },
  { id: "T7_FOOD_OMELETTE", name: "Omelete (T7)" },
  { id: "T8_FOOD_OMELETTE", name: "Omelete (T8)" },
  { id: "T4_FOOD_STEW", name: "Gisado (T4)" },
  { id: "T6_FOOD_STEW", name: "Gisado (T6)" },
  { id: "T7_FOOD_STEW", name: "Gisado (T7)" },
  { id: "T8_FOOD_STEW", name: "Gisado (T8)" },
  { id: "T4_FOOD_PIE", name: "Torta (T4)" },
  { id: "T6_FOOD_PIE", name: "Torta (T6)" },
  // Raw Resources
  { id: "T4_ORE", name: "Minério de Ferro (T4)" },
  { id: "T5_ORE", name: "Minério de Titânio (T5)" },
  { id: "T6_ORE", name: "Minério de Runas (T6)" },
  { id: "T7_ORE", name: "Minério de Meteorito (T7)" },
  { id: "T8_ORE", name: "Minério de Adamantio (T8)" },
  { id: "T4_FIBER", name: "Cânhamo (T4)" },
  { id: "T5_FIBER", name: "Algodão do Céu (T5)" },
  { id: "T6_FIBER", name: "Algodão Âmbar (T6)" },
  { id: "T7_FIBER", name: "Algodão do Sol (T7)" },
  { id: "T8_FIBER", name: "Algodão Fantasma (T8)" },
  { id: "T4_HIDE", name: "Couro Médio (T4)" },
  { id: "T5_HIDE", name: "Couro Pesado (T5)" },
  { id: "T6_HIDE", name: "Couro Robusto (T6)" },
  { id: "T7_HIDE", name: "Couro Grosso (T7)" },
  { id: "T8_HIDE", name: "Couro Resiliente (T8)" },
  { id: "T4_LOG", name: "Tronco de Pinheiro (T4)" },
  { id: "T5_LOG", name: "Tronco de Cedro (T5)" },
  { id: "T6_LOG", name: "Tronco de Bloqueio (T6)" },
  { id: "T7_LOG", name: "Tronco de Carvalho (T7)" },
  { id: "T8_LOG", name: "Tronco de Whitewood (T8)" },
  { id: "T4_ROCK", name: "Travertino (T4)" },
  { id: "T5_ROCK", name: "Granito (T5)" },
  { id: "T6_ROCK", name: "Ardósia (T6)" },
  { id: "T7_ROCK", name: "Basalto (T7)" },
  { id: "T8_ROCK", name: "Mármore (T8)" },
  // Faction Capes
  { id: "T4_CAPEITEM_MARTLOCK", name: "Capa de Martlock (T4)" },
  { id: "T6_CAPEITEM_MARTLOCK", name: "Capa de Martlock (T6)" },
  { id: "T8_CAPEITEM_MARTLOCK", name: "Capa de Martlock (T8)" },
  { id: "T4_CAPEITEM_LYMHURST", name: "Capa de Lymhurst (T4)" },
  { id: "T6_CAPEITEM_LYMHURST", name: "Capa de Lymhurst (T6)" },
  { id: "T8_CAPEITEM_LYMHURST", name: "Capa de Lymhurst (T8)" },
  { id: "T4_CAPEITEM_FORTSTERLING", name: "Capa de Fort Sterling (T4)" },
  { id: "T6_CAPEITEM_FORTSTERLING", name: "Capa de Fort Sterling (T6)" },
  { id: "T8_CAPEITEM_FORTSTERLING", name: "Capa de Fort Sterling (T8)" },
  { id: "T4_CAPEITEM_BRIDGEWATCH", name: "Capa de Bridgewatch (T4)" },
  { id: "T6_CAPEITEM_BRIDGEWATCH", name: "Capa de Bridgewatch (T6)" },
  { id: "T8_CAPEITEM_BRIDGEWATCH", name: "Capa de Bridgewatch (T8)" },
  { id: "T4_CAPEITEM_THETFORD", name: "Capa de Thetford (T4)" },
  { id: "T6_CAPEITEM_THETFORD", name: "Capa de Thetford (T6)" },
  { id: "T8_CAPEITEM_THETFORD", name: "Capa de Thetford (T8)" },
  { id: "T4_CAPEITEM_CAERLEON", name: "Capa de Caerleon (T4)" },
  { id: "T6_CAPEITEM_CAERLEON", name: "Capa de Caerleon (T6)" },
  { id: "T8_CAPEITEM_CAERLEON", name: "Capa de Caerleon (T8)" },
  // Royal Sigils
  { id: "T4_ROYAL_SIGIL", name: "Insígnia Real (T4)" },
  { id: "T5_ROYAL_SIGIL", name: "Insígnia Real (T5)" },
  { id: "T6_ROYAL_SIGIL", name: "Insígnia Real (T6)" },
  { id: "T7_ROYAL_SIGIL", name: "Insígnia Real (T7)" },
  { id: "T8_ROYAL_SIGIL", name: "Insígnia Real (T8)" },
  // Crystal Weapons
  { id: "T4_2H_CRYSTAL_SWORD", name: "Espada de Cristal (T4)" },
  { id: "T6_2H_CRYSTAL_SWORD", name: "Espada de Cristal (T6)" },
  { id: "T8_2H_CRYSTAL_SWORD", name: "Espada de Cristal (T8)" },
  { id: "T4_2H_CRYSTAL_AXE", name: "Machado de Cristal (T4)" },
  { id: "T6_2H_CRYSTAL_AXE", name: "Machado de Cristal (T6)" },
  { id: "T8_2H_CRYSTAL_AXE", name: "Machado de Cristal (T8)" },
  { id: "T4_2H_CRYSTAL_MACE", name: "Maça de Cristal (T4)" },
  { id: "T6_2H_CRYSTAL_MACE", name: "Maça de Cristal (T6)" },
  { id: "T8_2H_CRYSTAL_MACE", name: "Maça de Cristal (T8)" },
  { id: "T4_2H_CRYSTAL_DAGGER", name: "Adaga de Cristal (T4)" },
  { id: "T6_2H_CRYSTAL_DAGGER", name: "Adaga de Cristal (T6)" },
  { id: "T8_2H_CRYSTAL_DAGGER", name: "Adaga de Cristal (T8)" },
  { id: "T4_2H_CRYSTAL_BOW", name: "Arco de Cristal (T4)" },
  { id: "T6_2H_CRYSTAL_BOW", name: "Arco de Cristal (T6)" },
  { id: "T8_2H_CRYSTAL_BOW", name: "Arco de Cristal (T8)" },
  { id: "T4_2H_CRYSTAL_FIRESTAFF", name: "Cajado de Fogo de Cristal (T4)" },
  { id: "T6_2H_CRYSTAL_FIRESTAFF", name: "Cajado de Fogo de Cristal (T6)" },
  { id: "T8_2H_CRYSTAL_FIRESTAFF", name: "Cajado de Fogo de Cristal (T8)" },
  // Faction Crests (Selo de Facção)
  { id: "T4_CREST_MARTLOCK", name: "Selo de Martlock (T4)" },
  { id: "T6_CREST_MARTLOCK", name: "Selo de Martlock (T6)" },
  { id: "T8_CREST_MARTLOCK", name: "Selo de Martlock (T8)" },
  { id: "T4_CREST_LYMHURST", name: "Selo de Lymhurst (T4)" },
  { id: "T6_CREST_LYMHURST", name: "Selo de Lymhurst (T6)" },
  { id: "T8_CREST_LYMHURST", name: "Selo de Lymhurst (T8)" },
  { id: "T4_CREST_FORTSTERLING", name: "Selo de Fort Sterling (T4)" },
  { id: "T6_CREST_FORTSTERLING", name: "Selo de Fort Sterling (T6)" },
  { id: "T8_CREST_FORTSTERLING", name: "Selo de Fort Sterling (T8)" },
  { id: "T4_CREST_BRIDGEWATCH", name: "Selo de Bridgewatch (T4)" },
  { id: "T6_CREST_BRIDGEWATCH", name: "Selo de Bridgewatch (T6)" },
  { id: "T8_CREST_BRIDGEWATCH", name: "Selo de Bridgewatch (T8)" },
  { id: "T4_CREST_THETFORD", name: "Selo de Thetford (T4)" },
  { id: "T6_CREST_THETFORD", name: "Selo de Thetford (T6)" },
  { id: "T8_CREST_THETFORD", name: "Selo de Thetford (T8)" },
  { id: "T4_CREST_CAERLEON", name: "Selo de Caerleon (T4)" },
  { id: "T6_CREST_CAERLEON", name: "Selo de Caerleon (T6)" },
  { id: "T8_CREST_CAERLEON", name: "Selo de Caerleon (T8)" },
  // Standard Weapons (Missing)
  { id: "T4_MAIN_BOW", name: "Arco (T4)" },
  { id: "T6_MAIN_BOW", name: "Arco (T6)" },
  { id: "T8_MAIN_BOW", name: "Arco (T8)" },
  { id: "T4_2H_WARBOW", name: "Arco de Guerra (T4)" },
  { id: "T6_2H_WARBOW", name: "Arco de Guerra (T6)" },
  { id: "T8_2H_WARBOW", name: "Arco de Guerra (T8)" },
  { id: "T4_2H_LONGBOW", name: "Arco Longo (T4)" },
  { id: "T6_2H_LONGBOW", name: "Arco Longo (T6)" },
  { id: "T8_2H_LONGBOW", name: "Arco Longo (T8)" },
  { id: "T4_MAIN_CROSSBOW", name: "Besta Leve (T4)" },
  { id: "T6_MAIN_CROSSBOW", name: "Besta Leve (T6)" },
  { id: "T8_MAIN_CROSSBOW", name: "Besta Leve (T8)" },
  { id: "T4_2H_CROSSBOW", name: "Besta Pesada (T4)" },
  { id: "T6_2H_CROSSBOW", name: "Besta Pesada (T6)" },
  { id: "T8_2H_CROSSBOW", name: "Besta Pesada (T8)" },
  { id: "T4_2H_CROSSBOWLARGE", name: "Besta (T4)" },
  { id: "T6_2H_CROSSBOWLARGE", name: "Besta (T6)" },
  { id: "T8_2H_CROSSBOWLARGE", name: "Besta (T8)" },
  { id: "T4_MAIN_DAGGER", name: "Adaga (T4)" },
  { id: "T6_MAIN_DAGGER", name: "Adaga (T6)" },
  { id: "T8_MAIN_DAGGER", name: "Adaga (T8)" },
  { id: "T4_2H_DAGGERPAIR", name: "Par de Adagas (T4)" },
  { id: "T6_2H_DAGGERPAIR", name: "Par de Adagas (T6)" },
  { id: "T8_2H_DAGGERPAIR", name: "Par de Adagas (T8)" },
  { id: "T4_2H_CLAWSSPELL", name: "Garras (T4)" },
  { id: "T6_2H_CLAWSSPELL", name: "Garras (T6)" },
  { id: "T8_2H_CLAWSSPELL", name: "Garras (T8)" },
  { id: "T4_MAIN_SPEAR", name: "Lança (T4)" },
  { id: "T6_MAIN_SPEAR", name: "Lança (T6)" },
  { id: "T8_MAIN_SPEAR", name: "Lança (T8)" },
  { id: "T4_2H_GLAIVE", name: "Glaive (T4)" },
  { id: "T6_2H_GLAIVE", name: "Glaive (T6)" },
  { id: "T8_2H_GLAIVE", name: "Glaive (T8)" },
  { id: "T4_2H_AXE", name: "Grande Machado (T4)" },
  { id: "T6_2H_AXE", name: "Grande Machado (T6)" },
  { id: "T8_2H_AXE", name: "Grande Machado (T8)" },
  { id: "T4_2H_HALBERD", name: "Alabarda (T4)" },
  { id: "T6_2H_HALBERD", name: "Alabarda (T6)" },
  { id: "T8_2H_HALBERD", name: "Alabarda (T8)" },
  { id: "T4_2H_CLAYMORE", name: "Montante (T4)" },
  { id: "T6_2H_CLAYMORE", name: "Montante (T6)" },
  { id: "T8_2H_CLAYMORE", name: "Montante (T8)" },
  { id: "T4_2H_DUALSWORD", name: "Espadas Duplas (T4)" },
  { id: "T6_2H_DUALSWORD", name: "Espadas Duplas (T6)" },
  { id: "T8_2H_DUALSWORD", name: "Espadas Duplas (T8)" },
  { id: "T4_MAIN_HAMMER", name: "Martelo (T4)" },
  { id: "T6_MAIN_HAMMER", name: "Martelo (T6)" },
  { id: "T8_MAIN_HAMMER", name: "Martelo (T8)" },
  { id: "T4_2H_POLEHAMMER", name: "Martelo de Poste (T4)" },
  { id: "T6_2H_POLEHAMMER", name: "Martelo de Poste (T6)" },
  { id: "T8_2H_POLEHAMMER", name: "Martelo de Poste (T8)" },
  { id: "T4_MAIN_MACE", name: "Maça (T4)" },
  { id: "T6_MAIN_MACE", name: "Maça (T6)" },
  { id: "T8_MAIN_MACE", name: "Maça (T8)" },
  { id: "T4_2H_MACE", name: "Maça Pesada (T4)" },
  { id: "T6_2H_MACE", name: "Maça Pesada (T6)" },
  { id: "T8_2H_MACE", name: "Maça Pesada (T8)" },
  { id: "T4_2H_QUARTERSTAFF", name: "Bastão (T4)" },
  { id: "T6_2H_QUARTERSTAFF", name: "Bastão (T6)" },
  { id: "T8_2H_QUARTERSTAFF", name: "Bastão (T8)" },
  { id: "T4_2H_IRONCLADEDSTAFF", name: "Bastão Revestido de Ferro (T4)" },
  { id: "T6_2H_IRONCLADEDSTAFF", name: "Bastão Revestido de Ferro (T6)" },
  { id: "T8_2H_IRONCLADEDSTAFF", name: "Bastão Revestido de Ferro (T8)" },
  { id: "T4_2H_KNUCKLES_SET1", name: "Luvas de Batalha (T4)" },
  { id: "T6_2H_KNUCKLES_SET1", name: "Luvas de Batalha (T6)" },
  { id: "T8_2H_KNUCKLES_SET1", name: "Luvas de Batalha (T8)" },
  // Artifact & Special Weapons
  { id: "T4_2H_GALATINE_HELL", name: "Par Galatine (T4)" },
  { id: "T6_2H_GALATINE_HELL", name: "Par Galatine (T6)" },
  { id: "T8_2H_GALATINE_HELL", name: "Par Galatine (T8)" },
  { id: "T4_MAIN_SCIMITAR_MORGANA", name: "Clarent Blade (T4)" },
  { id: "T6_MAIN_SCIMITAR_MORGANA", name: "Clarent Blade (T6)" },
  { id: "T8_MAIN_SCIMITAR_MORGANA", name: "Clarent Blade (T8)" },
  { id: "T4_2H_KINGMAKER_AVALON", name: "Rei Caído (T4)" },
  { id: "T6_2H_KINGMAKER_AVALON", name: "Rei Caído (T6)" },
  { id: "T8_2H_KINGMAKER_AVALON", name: "Rei Caído (T8)" },
  { id: "T4_2H_BEARPAWS_HELL", name: "Garras de Urso (T4)" },
  { id: "T6_2H_BEARPAWS_HELL", name: "Garras de Urso (T6)" },
  { id: "T8_2H_BEARPAWS_HELL", name: "Garras de Urso (T8)" },
  { id: "T4_2H_AXE_HELL", name: "Machado Infernal (T4)" },
  { id: "T6_2H_AXE_HELL", name: "Machado Infernal (T6)" },
  { id: "T8_2H_AXE_HELL", name: "Machado Infernal (T8)" },
  { id: "T4_2H_FLAIL", name: "Estrela da Manhã (T4)" },
  { id: "T6_2H_FLAIL", name: "Estrela da Manhã (T6)" },
  { id: "T8_2H_FLAIL", name: "Estrela da Manhã (T8)" },
  { id: "T4_2H_MACE_MORGANA", name: "Maça de Camlann (T4)" },
  { id: "T6_2H_MACE_MORGANA", name: "Maça de Camlann (T6)" },
  { id: "T8_2H_MACE_MORGANA", name: "Maça de Camlann (T8)" },
  { id: "T4_MAIN_MACE_HELL", name: "Maça Incubus (T4)" },
  { id: "T6_MAIN_MACE_HELL", name: "Maça Incubus (T6)" },
  { id: "T8_MAIN_MACE_HELL", name: "Maça Incubus (T8)" },
  { id: "T4_2H_RAM_KEEPER", name: "Guardião do Bosque (T4)" },
  { id: "T6_2H_RAM_KEEPER", name: "Guardião do Bosque (T6)" },
  { id: "T8_2H_RAM_KEEPER", name: "Guardião do Bosque (T8)" },
  { id: "T4_2H_HAMMER_UNDEAD", name: "Tumba (T4)" },
  { id: "T6_2H_HAMMER_UNDEAD", name: "Tumba (T6)" },
  { id: "T8_2H_HAMMER_UNDEAD", name: "Tumba (T8)" },
  { id: "T4_2H_WARSPEAR_UNDEAD", name: "Lança de Guerra (T4)" },
  { id: "T6_2H_WARSPEAR_UNDEAD", name: "Lança de Guerra (T6)" },
  { id: "T8_2H_WARSPEAR_UNDEAD", name: "Lança de Guerra (T8)" },
  { id: "T4_MAIN_SPEAR_KEEPER", name: "Lança Espiral (T4)" },
  { id: "T6_MAIN_SPEAR_KEEPER", name: "Lança Espiral (T6)" },
  { id: "T8_MAIN_SPEAR_KEEPER", name: "Lança Espiral (T8)" },
  { id: "T4_2H_TRIDENT_HELL", name: "Garfo da Trindade (T4)" },
  { id: "T6_2H_TRIDENT_HELL", name: "Garfo da Trindade (T6)" },
  { id: "T8_2H_TRIDENT_HELL", name: "Garfo da Trindade (T8)" },
  { id: "T4_MAIN_SPEAR_MORGANA", name: "Lança da Heron (T4)" },
  { id: "T6_MAIN_SPEAR_MORGANA", name: "Lança da Heron (T6)" },
  { id: "T8_MAIN_SPEAR_MORGANA", name: "Lança da Heron (T8)" },
  { id: "T4_2H_DOUBLEBLADEDSTAFF", name: "Bastão Duplo (T4)" },
  { id: "T6_2H_DOUBLEBLADEDSTAFF", name: "Bastão Duplo (T6)" },
  { id: "T8_2H_DOUBLEBLADEDSTAFF", name: "Bastão Duplo (T8)" },
  { id: "T4_2H_COMBATSTAFF_MORGANA", name: "Bastão do Monge Negro (T4)" },
  { id: "T6_2H_COMBATSTAFF_MORGANA", name: "Bastão do Monge Negro (T6)" },
  { id: "T8_2H_COMBATSTAFF_MORGANA", name: "Bastão do Monge Negro (T8)" },
  { id: "T4_2H_TWINSCYTHE_HELL", name: "Bastão Soulscythe (T4)" },
  { id: "T6_2H_TWINSCYTHE_HELL", name: "Bastão Soulscythe (T6)" },
  { id: "T8_2H_TWINSCYTHE_HELL", name: "Bastão Soulscythe (T8)" },
  { id: "T4_2H_DAGGER_MORGANA", name: "Dádivas da Morte (T4)" },
  { id: "T6_2H_DAGGER_MORGANA", name: "Dádivas da Morte (T6)" },
  { id: "T8_2H_DAGGER_MORGANA", name: "Dádivas da Morte (T8)" },
  { id: "T4_MAIN_DAGGER_HELL", name: "Punhal Sombrio (T4)" },
  { id: "T6_MAIN_DAGGER_HELL", name: "Punhal Sombrio (T6)" },
  { id: "T8_MAIN_DAGGER_HELL", name: "Punhal Sombrio (T8)" },
  { id: "T4_2H_BOW_HELL", name: "Arco Sussurrante (T4)" },
  { id: "T6_2H_BOW_HELL", name: "Arco Sussurrante (T6)" },
  { id: "T8_2H_BOW_HELL", name: "Arco Sussurrante (T8)" },
  { id: "T4_2H_BOW_KEEPER", name: "Arco do Mau Presságio (T4)" },
  { id: "T6_2H_BOW_KEEPER", name: "Arco do Mau Presságio (T6)" },
  { id: "T8_2H_BOW_KEEPER", name: "Arco do Mau Presságio (T8)" },
  { id: "T4_2H_SIEGEBOW_HELL", name: "Arco de Cerco (T4)" },
  { id: "T6_2H_SIEGEBOW_HELL", name: "Arco de Cerco (T6)" },
  { id: "T8_2H_SIEGEBOW_HELL", name: "Arco de Cerco (T8)" },
  { id: "T4_2H_REPEATINGCROSSBOW_UNDEAD", name: "Besta Energética (T4)" },
  { id: "T6_2H_REPEATINGCROSSBOW_UNDEAD", name: "Besta Energética (T6)" },
  { id: "T8_2H_REPEATINGCROSSBOW_UNDEAD", name: "Besta Energética (T8)" },
  { id: "T4_2H_KNUCKLES_SET2", name: "Manoplas (T4)" },
  { id: "T6_2H_KNUCKLES_SET2", name: "Manoplas (T6)" },
  { id: "T8_2H_KNUCKLES_SET2", name: "Manoplas (T8)" },
  { id: "T4_2H_KNUCKLES_SET3", name: "Punhos Espirituais (T4)" },
  { id: "T6_2H_KNUCKLES_SET3", name: "Punhos Espirituais (T6)" },
  { id: "T8_2H_KNUCKLES_SET3", name: "Punhos Espirituais (T8)" },
  { id: "T4_2H_KNUCKLES_HELL", name: "Punhos da Ira (T4)" },
  { id: "T6_2H_KNUCKLES_HELL", name: "Punhos da Ira (T6)" },
  { id: "T8_2H_KNUCKLES_HELL", name: "Punhos da Ira (T8)" },
  { id: "T4_2H_KNUCKLES_KEEPER", name: "Luvas da Ursa (T4)" },
  { id: "T6_2H_KNUCKLES_KEEPER", name: "Luvas da Ursa (T6)" },
  { id: "T8_2H_KNUCKLES_KEEPER", name: "Luvas da Ursa (T8)" },
  { id: "T4_2H_NATURESTAFF_HELL", name: "Cajado do Arvoredo (T4)" },
  { id: "T6_2H_NATURESTAFF_HELL", name: "Cajado do Arvoredo (T6)" },
  { id: "T8_2H_NATURESTAFF_HELL", name: "Cajado do Arvoredo (T8)" },
  { id: "T4_2H_NATURESTAFF_KEEPER", name: "Cajado de Ferro (T4)" },
  { id: "T6_2H_NATURESTAFF_KEEPER", name: "Cajado de Ferro (T6)" },
  { id: "T8_2H_NATURESTAFF_KEEPER", name: "Cajado de Ferro (T8)" },
  // Faction Capes (Enchanted)
  { id: "T4_CAPEITEM_MARTLOCK@1", name: "Capa de Martlock (T4.1)" },
  { id: "T4_CAPEITEM_MARTLOCK@2", name: "Capa de Martlock (T4.2)" },
  { id: "T4_CAPEITEM_MARTLOCK@3", name: "Capa de Martlock (T4.3)" },
  { id: "T5_CAPEITEM_MARTLOCK@1", name: "Capa de Martlock (T5.1)" },
  { id: "T5_CAPEITEM_MARTLOCK@2", name: "Capa de Martlock (T5.2)" },
  { id: "T5_CAPEITEM_MARTLOCK@3", name: "Capa de Martlock (T5.3)" },
  { id: "T6_CAPEITEM_MARTLOCK@1", name: "Capa de Martlock (T6.1)" },
  { id: "T6_CAPEITEM_MARTLOCK@2", name: "Capa de Martlock (T6.2)" },
  { id: "T6_CAPEITEM_MARTLOCK@3", name: "Capa de Martlock (T6.3)" },
  { id: "T4_CAPEITEM_LYMHURST@1", name: "Capa de Lymhurst (T4.1)" },
  { id: "T4_CAPEITEM_LYMHURST@2", name: "Capa de Lymhurst (T4.2)" },
  { id: "T4_CAPEITEM_LYMHURST@3", name: "Capa de Lymhurst (T4.3)" },
  { id: "T5_CAPEITEM_LYMHURST@1", name: "Capa de Lymhurst (T5.1)" },
  { id: "T5_CAPEITEM_LYMHURST@2", name: "Capa de Lymhurst (T5.2)" },
  { id: "T5_CAPEITEM_LYMHURST@3", name: "Capa de Lymhurst (T5.3)" },
  { id: "T6_CAPEITEM_LYMHURST@1", name: "Capa de Lymhurst (T6.1)" },
  { id: "T6_CAPEITEM_LYMHURST@2", name: "Capa de Lymhurst (T6.2)" },
  { id: "T6_CAPEITEM_LYMHURST@3", name: "Capa de Lymhurst (T6.3)" },
  { id: "T4_CAPEITEM_FORTSTERLING@1", name: "Capa de Fort Sterling (T4.1)" },
  { id: "T4_CAPEITEM_FORTSTERLING@2", name: "Capa de Fort Sterling (T4.2)" },
  { id: "T4_CAPEITEM_FORTSTERLING@3", name: "Capa de Fort Sterling (T4.3)" },
  { id: "T5_CAPEITEM_FORTSTERLING@1", name: "Capa de Fort Sterling (T5.1)" },
  { id: "T5_CAPEITEM_FORTSTERLING@2", name: "Capa de Fort Sterling (T5.2)" },
  { id: "T5_CAPEITEM_FORTSTERLING@3", name: "Capa de Fort Sterling (T5.3)" },
  { id: "T6_CAPEITEM_FORTSTERLING@1", name: "Capa de Fort Sterling (T6.1)" },
  { id: "T6_CAPEITEM_FORTSTERLING@2", name: "Capa de Fort Sterling (T6.2)" },
  { id: "T6_CAPEITEM_FORTSTERLING@3", name: "Capa de Fort Sterling (T6.3)" },
  { id: "T4_CAPEITEM_BRIDGEWATCH@1", name: "Capa de Bridgewatch (T4.1)" },
  { id: "T4_CAPEITEM_BRIDGEWATCH@2", name: "Capa de Bridgewatch (T4.2)" },
  { id: "T4_CAPEITEM_BRIDGEWATCH@3", name: "Capa de Bridgewatch (T4.3)" },
  { id: "T5_CAPEITEM_BRIDGEWATCH@1", name: "Capa de Bridgewatch (T5.1)" },
  { id: "T5_CAPEITEM_BRIDGEWATCH@2", name: "Capa de Bridgewatch (T5.2)" },
  { id: "T5_CAPEITEM_BRIDGEWATCH@3", name: "Capa de Bridgewatch (T5.3)" },
  { id: "T6_CAPEITEM_BRIDGEWATCH@1", name: "Capa de Bridgewatch (T6.1)" },
  { id: "T6_CAPEITEM_BRIDGEWATCH@2", name: "Capa de Bridgewatch (T6.2)" },
  { id: "T6_CAPEITEM_BRIDGEWATCH@3", name: "Capa de Bridgewatch (T6.3)" },
  { id: "T4_CAPEITEM_THETFORD@1", name: "Capa de Thetford (T4.1)" },
  { id: "T4_CAPEITEM_THETFORD@2", name: "Capa de Thetford (T4.2)" },
  { id: "T4_CAPEITEM_THETFORD@3", name: "Capa de Thetford (T4.3)" },
  { id: "T5_CAPEITEM_THETFORD@1", name: "Capa de Thetford (T5.1)" },
  { id: "T5_CAPEITEM_THETFORD@2", name: "Capa de Thetford (T5.2)" },
  { id: "T5_CAPEITEM_THETFORD@3", name: "Capa de Thetford (T5.3)" },
  { id: "T6_CAPEITEM_THETFORD@1", name: "Capa de Thetford (T6.1)" },
  { id: "T6_CAPEITEM_THETFORD@2", name: "Capa de Thetford (T6.2)" },
  { id: "T6_CAPEITEM_THETFORD@3", name: "Capa de Thetford (T6.3)" },
  { id: "T4_CAPEITEM_CAERLEON@1", name: "Capa de Caerleon (T4.1)" },
  { id: "T4_CAPEITEM_CAERLEON@2", name: "Capa de Caerleon (T4.2)" },
  { id: "T4_CAPEITEM_CAERLEON@3", name: "Capa de Caerleon (T4.3)" },
  { id: "T5_CAPEITEM_CAERLEON@1", name: "Capa de Caerleon (T5.1)" },
  { id: "T5_CAPEITEM_CAERLEON@2", name: "Capa de Caerleon (T5.2)" },
  { id: "T5_CAPEITEM_CAERLEON@3", name: "Capa de Caerleon (T5.3)" },
  { id: "T6_CAPEITEM_CAERLEON@1", name: "Capa de Caerleon (T6.1)" },
  { id: "T6_CAPEITEM_CAERLEON@2", name: "Capa de Caerleon (T6.2)" },
  { id: "T6_CAPEITEM_CAERLEON@3", name: "Capa de Caerleon (T6.3)" },
  // Artifact Armor Sets
  // Graveguard (Plate)
  { id: "T4_HEAD_PLATE_HELL", name: "Elmo de Graveguard (T4)" },
  { id: "T5_HEAD_PLATE_HELL", name: "Elmo de Graveguard (T5)" },
  { id: "T6_HEAD_PLATE_HELL", name: "Elmo de Graveguard (T6)" },
  { id: "T4_ARMOR_PLATE_HELL", name: "Armadura de Graveguard (T4)" },
  { id: "T5_ARMOR_PLATE_HELL", name: "Armadura de Graveguard (T5)" },
  { id: "T6_ARMOR_PLATE_HELL", name: "Armadura de Graveguard (T6)" },
  { id: "T4_SHOES_PLATE_HELL", name: "Botas de Graveguard (T4)" },
  { id: "T5_SHOES_PLATE_HELL", name: "Botas de Graveguard (T5)" },
  { id: "T6_SHOES_PLATE_HELL", name: "Botas de Graveguard (T6)" },
  // Stalker (Leather)
  { id: "T4_HEAD_LEATHER_HELL", name: "Capuz de Espreitador (T4)" },
  { id: "T5_HEAD_LEATHER_HELL", name: "Capuz de Espreitador (T5)" },
  { id: "T6_HEAD_LEATHER_HELL", name: "Capuz de Espreitador (T6)" },
  { id: "T4_ARMOR_LEATHER_HELL", name: "Jaqueta de Espreitador (T4)" },
  { id: "T5_ARMOR_LEATHER_HELL", name: "Jaqueta de Espreitador (T5)" },
  { id: "T6_ARMOR_LEATHER_HELL", name: "Jaqueta de Espreitador (T6)" },
  { id: "T4_SHOES_LEATHER_HELL", name: "Sapatos de Espreitador (T4)" },
  { id: "T5_SHOES_LEATHER_HELL", name: "Sapatos de Espreitador (T5)" },
  { id: "T6_SHOES_LEATHER_HELL", name: "Sapatos de Espreitador (T6)" },
  // Cultist (Cloth)
  { id: "T4_HEAD_CLOTH_HELL", name: "Capuz de Cultista (T4)" },
  { id: "T5_HEAD_CLOTH_HELL", name: "Capuz de Cultista (T5)" },
  { id: "T6_HEAD_CLOTH_HELL", name: "Capuz de Cultista (T6)" },
  { id: "T4_ARMOR_CLOTH_HELL", name: "Robe de Cultista (T4)" },
  { id: "T5_ARMOR_CLOTH_HELL", name: "Robe de Cultista (T5)" },
  { id: "T6_ARMOR_CLOTH_HELL", name: "Robe de Cultista (T6)" },
  { id: "T4_SHOES_CLOTH_HELL", name: "Sandálias de Cultista (T4)" },
  { id: "T5_SHOES_CLOTH_HELL", name: "Sandálias de Cultista (T5)" },
  { id: "T6_SHOES_CLOTH_HELL", name: "Sandálias de Cultista (T6)" },
  // Fiend (Cloth)
  { id: "T4_HEAD_CLOTH_KEEPER", name: "Capuz de Druida (T4)" },
  { id: "T5_HEAD_CLOTH_KEEPER", name: "Capuz de Druida (T5)" },
  { id: "T6_HEAD_CLOTH_KEEPER", name: "Capuz de Druida (T6)" },
  { id: "T4_ARMOR_CLOTH_KEEPER", name: "Robe de Druida (T4)" },
  { id: "T5_ARMOR_CLOTH_KEEPER", name: "Robe de Druida (T5)" },
  { id: "T6_ARMOR_CLOTH_KEEPER", name: "Robe de Druida (T6)" },
  { id: "T4_SHOES_CLOTH_KEEPER", name: "Sandálias de Druida (T4)" },
  { id: "T5_SHOES_CLOTH_KEEPER", name: "Sandálias de Druida (T5)" },
  { id: "T6_SHOES_CLOTH_KEEPER", name: "Sandálias de Druida (T6)" },
  // Hellion (Leather)
  { id: "T4_HEAD_LEATHER_MORGANA", name: "Capuz de Helion (T4)" },
  { id: "T5_HEAD_LEATHER_MORGANA", name: "Capuz de Helion (T5)" },
  { id: "T6_HEAD_LEATHER_MORGANA", name: "Capuz de Helion (T6)" },
  { id: "T4_ARMOR_LEATHER_MORGANA", name: "Jaqueta de Helion (T4)" },
  { id: "T5_ARMOR_LEATHER_MORGANA", name: "Jaqueta de Helion (T5)" },
  { id: "T6_ARMOR_LEATHER_MORGANA", name: "Jaqueta de Helion (T6)" },
  { id: "T4_SHOES_LEATHER_MORGANA", name: "Sapatos de Helion (T4)" },
  { id: "T5_SHOES_LEATHER_MORGANA", name: "Sapatos de Helion (T5)" },
  { id: "T6_SHOES_LEATHER_MORGANA", name: "Sapatos de Helion (T6)" },
  // Judicator (Plate)
  { id: "T4_HEAD_PLATE_UNDEAD", name: "Elmo de Judicante (T4)" },
  { id: "T5_HEAD_PLATE_UNDEAD", name: "Elmo de Judicante (T5)" },
  { id: "T6_HEAD_PLATE_UNDEAD", name: "Elmo de Judicante (T6)" },
  { id: "T4_ARMOR_PLATE_UNDEAD", name: "Armadura de Judicante (T4)" },
  { id: "T5_ARMOR_PLATE_UNDEAD", name: "Armadura de Judicante (T5)" },
  { id: "T6_ARMOR_PLATE_UNDEAD", name: "Armadura de Judicante (T6)" },
  { id: "T4_SHOES_PLATE_UNDEAD", name: "Botas de Judicante (T4)" },
  { id: "T5_SHOES_PLATE_UNDEAD", name: "Botas de Judicante (T5)" },
  { id: "T6_SHOES_PLATE_UNDEAD", name: "Botas de Judicante (T6)" },
  // Specter (Leather)
  { id: "T4_HEAD_LEATHER_UNDEAD", name: "Capuz de Espectro (T4)" },
  { id: "T6_HEAD_LEATHER_UNDEAD", name: "Capuz de Espectro (T6)" },
  { id: "T8_HEAD_LEATHER_UNDEAD", name: "Capuz de Espectro (T8)" },
  { id: "T4_ARMOR_LEATHER_UNDEAD", name: "Jaqueta de Espectro (T4)" },
  { id: "T6_ARMOR_LEATHER_UNDEAD", name: "Jaqueta de Espectro (T6)" },
  { id: "T8_ARMOR_LEATHER_UNDEAD", name: "Jaqueta de Espectro (T8)" },
  { id: "T4_SHOES_LEATHER_UNDEAD", name: "Sapatos de Espectro (T4)" },
  { id: "T6_SHOES_LEATHER_UNDEAD", name: "Sapatos de Espectro (T6)" },
  { id: "T8_SHOES_LEATHER_UNDEAD", name: "Sapatos de Espectro (T8)" },
  // Tenacity (Plate)
  { id: "T4_HEAD_PLATE_AVALON", name: "Elmo da Tenacidade (T4)" },
  { id: "T6_HEAD_PLATE_AVALON", name: "Elmo da Tenacidade (T6)" },
  { id: "T8_HEAD_PLATE_AVALON", name: "Elmo da Tenacidade (T8)" },
  { id: "T4_ARMOR_PLATE_AVALON", name: "Armadura da Tenacidade (T4)" },
  { id: "T6_ARMOR_PLATE_AVALON", name: "Armadura da Tenacidade (T6)" },
  { id: "T8_ARMOR_PLATE_AVALON", name: "Armadura da Tenacidade (T8)" },
  { id: "T4_SHOES_PLATE_AVALON", name: "Botas da Tenacidade (T4)" },
  { id: "T6_SHOES_PLATE_AVALON", name: "Botas da Tenacidade (T6)" },
  { id: "T8_SHOES_PLATE_AVALON", name: "Botas da Tenacidade (T8)" },
  // Gathering Gear - Miner
  { id: "T4_HEAD_GATHERER_ORE", name: "Capuz de Minerador (T4)" },
  { id: "T5_HEAD_GATHERER_ORE", name: "Capuz de Minerador (T5)" },
  { id: "T6_HEAD_GATHERER_ORE", name: "Capuz de Minerador (T6)" },
  { id: "T4_ARMOR_GATHERER_ORE", name: "Garba de Minerador (T4)" },
  { id: "T5_ARMOR_GATHERER_ORE", name: "Garba de Minerador (T5)" },
  { id: "T6_ARMOR_GATHERER_ORE", name: "Garba de Minerador (T6)" },
  { id: "T4_SHOES_GATHERER_ORE", name: "Botas de Minerador (T4)" },
  { id: "T5_SHOES_GATHERER_ORE", name: "Botas de Minerador (T5)" },
  { id: "T6_SHOES_GATHERER_ORE", name: "Botas de Minerador (T6)" },
  // Gathering Gear - Skinner
  { id: "T4_HEAD_GATHERER_HIDE", name: "Capuz de Esfolador (T4)" },
  { id: "T5_HEAD_GATHERER_HIDE", name: "Capuz de Esfolador (T5)" },
  { id: "T6_HEAD_GATHERER_HIDE", name: "Capuz de Esfolador (T6)" },
  { id: "T4_ARMOR_GATHERER_HIDE", name: "Garba de Esfolador (T4)" },
  { id: "T5_ARMOR_GATHERER_HIDE", name: "Garba de Esfolador (T5)" },
  { id: "T6_ARMOR_GATHERER_HIDE", name: "Garba de Esfolador (T6)" },
  { id: "T4_SHOES_GATHERER_HIDE", name: "Botas de Esfolador (T4)" },
  { id: "T5_SHOES_GATHERER_HIDE", name: "Botas de Esfolador (T5)" },
  { id: "T6_SHOES_GATHERER_HIDE", name: "Botas de Esfolador (T6)" },
  // Gathering Gear - Lumberjack
  { id: "T4_HEAD_GATHERER_WOOD", name: "Capuz de Lenhador (T4)" },
  { id: "T5_HEAD_GATHERER_WOOD", name: "Capuz de Lenhador (T5)" },
  { id: "T6_HEAD_GATHERER_WOOD", name: "Capuz de Lenhador (T6)" },
  { id: "T4_ARMOR_GATHERER_WOOD", name: "Garba de Lenhador (T4)" },
  { id: "T5_ARMOR_GATHERER_WOOD", name: "Garba de Lenhador (T5)" },
  { id: "T6_ARMOR_GATHERER_WOOD", name: "Garba de Lenhador (T6)" },
  { id: "T4_SHOES_GATHERER_WOOD", name: "Botas de Lenhador (T4)" },
  { id: "T5_SHOES_GATHERER_WOOD", name: "Botas de Lenhador (T5)" },
  { id: "T6_SHOES_GATHERER_WOOD", name: "Botas de Lenhador (T6)" },
  // More Artifact Weapons
  { id: "T4_2H_CLEAVER_HELL", name: "Lâminas de Sangue (T4)" },
  { id: "T6_2H_CLEAVER_HELL", name: "Lâminas de Sangue (T6)" },
  { id: "T8_2H_CLEAVER_HELL", name: "Lâminas de Sangue (T8)" },
  { id: "T4_2H_DUALSCYTHE_HELL", name: "Foices Infernais (T4)" },
  { id: "T6_2H_DUALSCYTHE_HELL", name: "Foices Infernais (T6)" },
  { id: "T8_2H_DUALSCYTHE_HELL", name: "Foices Infernais (T8)" },
  { id: "T4_2H_IRONGAUNTLETS_HELL", name: "Manoplas de Ferro (T4)" },
  { id: "T6_2H_IRONGAUNTLETS_HELL", name: "Manoplas de Ferro (T6)" },
  { id: "T8_2H_IRONGAUNTLETS_HELL", name: "Manoplas de Ferro (T8)" },
  { id: "T4_2H_SCYTHE_HELL", name: "Foice de Morte (T4)" },
  { id: "T6_2H_SCYTHE_HELL", name: "Foice de Morte (T6)" },
  { id: "T8_2H_SCYTHE_HELL", name: "Foice de Morte (T8)" },
  // Arcane Staffs
  { id: "T4_MAIN_ARCANESTAFF", name: "Cajado Arcano (T4)" },
  { id: "T6_MAIN_ARCANESTAFF", name: "Cajado Arcano (T6)" },
  { id: "T8_MAIN_ARCANESTAFF", name: "Cajado Arcano (T8)" },
  { id: "T4_2H_ARCANESTAFF", name: "Grande Cajado Arcano (T4)" },
  { id: "T6_2H_ARCANESTAFF", name: "Grande Cajado Arcano (T6)" },
  { id: "T8_2H_ARCANESTAFF", name: "Grande Cajado Arcano (T8)" },
  { id: "T4_2H_ENIGMATICSTAFF", name: "Cajado Enigmático (T4)" },
  { id: "T6_2H_ENIGMATICSTAFF", name: "Cajado Enigmático (T6)" },
  { id: "T8_2H_ENIGMATICSTAFF", name: "Cajado Enigmático (T8)" },
  // Cursed Staffs
  { id: "T4_MAIN_CURSESTAFF", name: "Cajado Amaldiçoado (T4)" },
  { id: "T6_MAIN_CURSESTAFF", name: "Cajado Amaldiçoado (T6)" },
  { id: "T8_MAIN_CURSESTAFF", name: "Cajado Amaldiçoado (T8)" },
  { id: "T4_2H_CURSESTAFF", name: "Grande Cajado Amaldiçoado (T4)" },
  { id: "T6_2H_CURSESTAFF", name: "Grande Cajado Amaldiçoado (T6)" },
  { id: "T8_2H_CURSESTAFF", name: "Grande Cajado Amaldiçoado (T8)" },
  { id: "T4_2H_DEMONICSTAFF", name: "Cajado Demoníaco (T4)" },
  { id: "T6_2H_DEMONICSTAFF", name: "Cajado Demoníaco (T6)" },
  { id: "T8_2H_DEMONICSTAFF", name: "Cajado Demoníaco (T8)" },
  // Frost Staffs
  { id: "T4_MAIN_FROSTSTAFF", name: "Cajado de Gelo (T4)" },
  { id: "T6_MAIN_FROSTSTAFF", name: "Cajado de Gelo (T6)" },
  { id: "T8_MAIN_FROSTSTAFF", name: "Cajado de Gelo (T8)" },
  { id: "T4_2H_FROSTSTAFF", name: "Grande Cajado de Gelo (T4)" },
  { id: "T6_2H_FROSTSTAFF", name: "Grande Cajado de Gelo (T6)" },
  { id: "T8_2H_FROSTSTAFF", name: "Grande Cajado de Gelo (T8)" },
  { id: "T4_2H_GLACIALSTAFF", name: "Cajado Glacial (T4)" },
  { id: "T6_2H_GLACIALSTAFF", name: "Cajado Glacial (T6)" },
  { id: "T8_2H_GLACIALSTAFF", name: "Cajado Glacial (T8)" },
  // Gathering Gear - Harvester (Fiber)
  { id: "T4_HEAD_GATHERER_FIBER", name: "Capuz de Ceifeiro (T4)" },
  { id: "T6_HEAD_GATHERER_FIBER", name: "Capuz de Ceifeiro (T6)" },
  { id: "T8_HEAD_GATHERER_FIBER", name: "Capuz de Ceifeiro (T8)" },
  { id: "T4_ARMOR_GATHERER_FIBER", name: "Garba de Ceifeiro (T4)" },
  { id: "T6_ARMOR_GATHERER_FIBER", name: "Garba de Ceifeiro (T6)" },
  { id: "T8_ARMOR_GATHERER_FIBER", name: "Garba de Ceifeiro (T8)" },
  { id: "T4_SHOES_GATHERER_FIBER", name: "Botas de Ceifeiro (T4)" },
  { id: "T6_SHOES_GATHERER_FIBER", name: "Botas de Ceifeiro (T6)" },
  { id: "T8_SHOES_GATHERER_FIBER", name: "Botas de Ceifeiro (T8)" },
  // Gathering Gear - Quarrier (Stone)
  { id: "T4_HEAD_GATHERER_STONE", name: "Capuz de Pedreiro (T4)" },
  { id: "T6_HEAD_GATHERER_STONE", name: "Capuz de Pedreiro (T6)" },
  { id: "T8_HEAD_GATHERER_STONE", name: "Capuz de Pedreiro (T8)" },
  { id: "T4_ARMOR_GATHERER_STONE", name: "Garba de Pedreiro (T4)" },
  { id: "T6_ARMOR_GATHERER_STONE", name: "Garba de Pedreiro (T6)" },
  { id: "T8_ARMOR_GATHERER_STONE", name: "Garba de Pedreiro (T8)" },
  { id: "T4_SHOES_GATHERER_STONE", name: "Botas de Pedreiro (T4)" },
  { id: "T6_SHOES_GATHERER_STONE", name: "Botas de Pedreiro (T6)" },
  { id: "T8_SHOES_GATHERER_STONE", name: "Botas de Pedreiro (T8)" },
  // Gathering Gear - Fisherman
  { id: "T4_HEAD_GATHERER_FISH", name: "Capuz de Pescador (T4)" },
  { id: "T6_HEAD_GATHERER_FISH", name: "Capuz de Pescador (T6)" },
  { id: "T8_HEAD_GATHERER_FISH", name: "Capuz de Pescador (T8)" },
  { id: "T4_ARMOR_GATHERER_FISH", name: "Garba de Pescador (T4)" },
  { id: "T6_ARMOR_GATHERER_FISH", name: "Garba de Pescador (T6)" },
  { id: "T8_ARMOR_GATHERER_FISH", name: "Garba de Pescador (T8)" },
  { id: "T4_SHOES_GATHERER_FISH", name: "Botas de Pescador (T4)" },
  { id: "T6_SHOES_GATHERER_FISH", name: "Botas de Pescador (T6)" },
  { id: "T8_SHOES_GATHERER_FISH", name: "Botas de Pescador (T8)" },
];
